### ISSUE TITLE
what about podcasting 2.0

### ISSUE THREAD

**Issue by deverman** [nostrocket/paidpodcasts#1]
How is this different than podcasting 2.0 which sounds like is supposed to stream sats? I haven't really tried it yet though.

**Comment by gsovereignty** [comment]
@deverman the main difference is that with "podcasting 2.0" you don't have to pay anything.

Payment would be mandatory with what I'm proposing here (if you want to access the latest stuff).

I don't believe the value for value idea will work for the vast majority of creators, they need something more solid.
